version: '3.9'
services:
  app:
    build: .
    image: clean-api:latest
    environment:
      - DB_DSN=postgresql+asyncpg://postgres:postgres@db:5432/app
      - JWT_SECRET=change-me
      - ENABLE_TRACING=false
      - CORS_ORIGINS=*
    ports:
      - "8000:8000"
    depends_on:
      - db
      - jaeger
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

